### PR TITLE
Add ASB annotation sticker

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
@neuroamanda: For your review! If you're happy, please merge. If not, send comments and I'll edit the file. When merged, I'll dispatch the stickers for printing. Thanks!

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
For some reason, the [`.svg` file (on GitHub)](https://github.com/RaoOfPhysics/asb-logo/blob/f183c38941f1449ea92d8bdcd7a3235732d97cf5/asb_sticker.svg) doesn't render the text on the side. It should appear here, in the `.png`:

asb_sticker

**Comment by neuroamanda** [comment]
I like it, but perhaps what I'd do is put the twitter handle and URL under "annotate me". also a bit jarring with the two fonts?

how many stickers? cost?

**Comment by RaoOfPhysics** [comment]
> I like it, but perhaps what I'd do is put the twitter handle and URL under "annotate me". also a bit jarring with the two fonts?

Will change to same font and put the Twitter handle + URL below the main text.

> how many stickers? cost?

I plan to get [50 for 53 USD](https://www.stickermule.com/products/square-stickers).

**Comment by RaoOfPhysics** [comment]
Updated version:

asb_sticker

**Comment by neuroamanda** [comment]
yeah, i like it. i probably also would like the old font, with the text centered below as it is now (also, slightly bigger?)

just a thought, to make these stickers as useful as possible for as long as possible. since there hasn't been much of any annotation, though that was part of the original plan, should it instead say something else? like "scicomm me" or "summarize me" or ...?

**Comment by RaoOfPhysics** [comment]
Following up privately.

**Pull request merged**
